on:
  push:
    branches:
      - main

jobs:
  push_to_remote:
    name: Push to remote
    runs-on: ubuntu-latest
    steps:
    - name: execute SSH commands       
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ls
            
    - name: cleanup
      run: rm -rf ~/.ssh
      
